# Ctilde

In [ ]:
%matplotlib inline

In [ ]:
from pylayers.antprop.channel import *
from pylayers.antprop.antenna import *

$\tilde{\mathbf{C}}$

In [ ]:
C=Ctilde()

In [ ]:
fGHz=np.r_[2.41,2.42]

In [ ]:
pa = np.r_[0.018,-2.75,0.98]
pb = np.r_[0.019,-2.75,0.98]
C.los(pa=pa,pb=pb,fGHz=fGHz)

In [ ]:
C

Ctilde
---------
(2,)
Nray : 1
fmin(GHz) : 2.41
fmax(GHz): 2.42
Nfreq : 2

In [ ]:
print C.pa
print C.pb

[ 0.018 -2.75   0.98 ]
[ 0.019 -2.75   0.98 ]

In [ ]:
print C.tang
print C.rang

[[ 1.57079633  0.        ]]
[[ 1.57079633 -3.14159265]]

# Antenna selection

In [ ]:
Aa = Antenna('Omni')
Ab = Antenna('3GPP_BackCenter_7.sh3')

In [ ]:
Aa.polar()

(<matplotlib.figure.Figure at 0x7f3b71c65bd0>,
 <matplotlib.projections.polar.PolarAxes at 0x7f3b71dda8d0>)

In [ ]:
Ab.polar(thd=90)

(<matplotlib.figure.Figure at 0x7f3b73c7cad0>,
 <matplotlib.projections.polar.PolarAxes at 0x7f3b71d07e50>)

In [ ]:
Ta = np.eye(3)
Tb = np.array([[-1,0,0],[0,-1,0],[0,0,1]])

In [ ]:
Tb

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [ ]:
C.tang.shape

(1, 2)

In [ ]:
Cl=C.locbas(Tt=Ta,Tr=Tb)

In [ ]:
H=Cl.prop2tran(a=Aa,b=Ab)

In [ ]:
print H.Gap
print H.Gat
print H.Gbp
print H.Gbt

[-inf]
[ 0.]
[-18.13467201+0.j]
[-7.86649093+0.j]

In [ ]:
H.ak

array([ 3.9922806])

In [ ]:
3/0.3

10.0

In [ ]:
C.tauk

array([ 0.00333333])

In [ ]:
L=32.4+20*np.log10(2.4)+20*np.log10(d)

In [ ]:
print L

[ 49.54664993]

In [ ]:
ak=H.ak[0]

In [ ]:
20*np.log10(ak)

12.024421158892364

In [ ]:
H

freq : 2.415 2.42 2
shape  : (1, 2)
tau (min, max) : 0.00333333333333 0.00333333333333
dist :0.001 0.001
Friis factor -j c/(4 pi f) has been applied

In [ ]:
H.y

array([[  2.75228375e-15-3.99640698j,   2.74659722e-15-3.98814994j]])

In [ ]:
ak

3.9922805962363754

In [ ]:
H.Fat.y

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [ ]:
H.Fap.y

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
H.Fbt.y

array([[ 0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j,
         0.40427367 +2.78419052e-16j,  0.40427367 +2.78419052e-16j]])

In [ ]:
C.Ctt.y

array([[1000.+0.j, 1000.+0.j]])

In [ ]:
C.Ctp.y

array([[ 0.+0.j,  0.+0.j]])

In [ ]:
H.alpha.y

array([[ 404.27366657 +2.78419052e-13j,  404.27366657 +2.78419052e-13j]])

In [ ]:
H.y

array([[  2.75228375e-15-3.99640698j,   2.74659722e-15-3.98814994j]])

In [ ]:
H.isFriis

True

In [ ]:
0.3/(4*np.pi*H.x)

array([ 0.0098854 ,  0.00986498])